### ISSUE TITLE
Cannot run sample?

### ISSUE THREAD

**Issue by ahmed-shehata** [ezhulenev/orderbook-dynamics#1]
I cannot run the sample, 

Error: Could not find or load main class order-book-dynamics.jar
- Also, where is the output file and in what format is it in? Could you please provide a little more documentation?

**Comment by ezhulenev** [comment]
you can run it directly from sbt with 'sbt run' command

**Comment by ahmed-shehata** [comment]
It requires some training data and validation data, could you please tell me what format should they be in? Or could you tell me where I can find some samples of those?

Also, what is the format of the output? Thanks!

**Comment by ezhulenev** [comment]
You can get free samples from NYSE ftp http://www.nyxdata.com/Data-Products/NYSE-OpenBook-History
